-- INSERTS TABELA PRODUTO
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P001', 'Notebook Dell', 'A');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P002', 'Mouse Gamer', 'I');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P003', 'Teclado Mecânico', 'A');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P004', 'Monitor 24 polegadas', 'A');
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES ('P005', 'Headset Bluetooth', 'I');

-- INSERTS TABELA PRODUTO_COSIF
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000001', 'P001', 'CLA001', 'A');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000002', 'P002', 'CLA002', 'I');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000003', 'P003', 'CLA003', 'A');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000004', 'P004', 'CLA001', 'A');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000005', 'P005', 'CLA002', 'I');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000006', 'P001', 'CLA004', 'A');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000007', 'P002', 'CLA003', 'A');
INSERT INTO PRODUTO_COSIF (COD_COSIF, COD_PRODUTO, COD_CLASSIFICACAO, STA_STATUS) VALUES ('COSIF000008', 'P003', 'CLA005', 'I');
